import { ApiProperty } from '@nestjs/swagger';

export class TopStoreItemDto {
  @ApiProperty({
    example: 'b3ca4897-40df-4d6b-b2ee-10b2a2202685',
    description: 'Store ID',
  })
  storeId!: string;

  @ApiProperty({ example: 'The Coffee House', description: 'Store Name' })
  storeName!: string;

  @ApiProperty({
    example: 450000,
    description: 'Total revenue generated by store',
  })
  totalRevenue!: number;

  @ApiProperty({
    example: 120,
    description: 'Total number of completed orders',
  })
  totalOrders!: number;

  @ApiProperty({ example: 4.8, description: 'Average rating of store' })
  ratingAvg!: number;
}
